name: Analyzer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup project
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: make setup

    - name: Check lint
      run: make lint
