name: Analyzer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup project
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: make setup

    - name: Check lint
      run: make lint

    - name: Code coverage
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: b08bec7eff0e2ff396c701db6eb99a231a50d7ca8b77050e4eb318d5fddbc5bc
      with:
        coverageCommand: make test-coverage
        coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
        debug: true
